### ISSUE TITLE
regarding  `EXAMPLE/` directory !

### ISSUE THREAD

**Issue by jorjis212** [mrhm-dev/100-plus-dom-projects#24]
## **Is the example directory deprecated? I can't find any contributed project's there. 🤔**

**Comment by mrhm-dev** [comment]
I just realized that. I will take a look at history.

**Comment by jorjis212** [comment]
## Okay, I think your last merge might cost previous projects. The example directory looked like this.

<br>

![image](https://user-images.githubusercontent.com/63964149/161420256-9e6ab35a-e483-459d-a3c1-ba85caeeb1fe.png)

**Comment by mrhm-dev** [comment]
Issue resolved
